import Config

local_env =
  case File.read(Path.expand("../../.env", __DIR__)) do
    {:ok, contents} ->
      contents
      |> String.split(~r/\r?\n/)
      |> Enum.reduce(%{}, fn line, values ->
        case String.split(String.trim(line), "=", parts: 2) do
          [key, value] when key != "" ->
            if String.starts_with?(key, "#") do
              values
            else
              Map.put(values, key, String.trim(value, "\"'"))
            end

          _ ->
            values
        end
      end)

    {:error, _reason} ->
      %{}
  end

env = fn key -> System.get_env(key) || Map.get(local_env, key) end
database_url = env.("DATABASE_URL")

if database_url && database_url != "" do
  config :theme1, Theme1.Repo, url: database_url
else
  postgres_user = env.("POSTGRES_USER")
  postgres_password = env.("POSTGRES_PASSWORD")
  postgres_database = env.("POSTGRES_DB")

  if Enum.any?([postgres_user, postgres_password, postgres_database], &(&1 in [nil, ""])) do
    raise """
    Database configuration is missing. Copy the repository's .env.example to .env,
    or set DATABASE_URL / POSTGRES_USER / POSTGRES_PASSWORD / POSTGRES_DB.
    """
  end

  postgres_port = String.to_integer(env.("POSTGRES_PORT") || "5432")

  config :theme1, Theme1.Repo,
    username: postgres_user,
    password: postgres_password,
    hostname: "localhost",
    port: postgres_port,
    database: postgres_database
end

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :theme1, Theme1Web.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: env.("SECRET_KEY_BASE"),
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :theme1, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
