FROM elixir:1.18.4-otp-28

WORKDIR /app
ENV MIX_ENV=dev

RUN mix local.hex --force && mix local.rebar --force
COPY mix.exs mix.lock ./
RUN mix deps.get
COPY . .

EXPOSE 4000
CMD ["sh", "-c", "mix deps.get && mix ecto.setup && mix phx.server"]
