```yaml
name: Mirroring

on:
  push:
  delete:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Mirror to Theme1
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@github.com:maurelK/Theme1.git
          ssh_private_key: ${{ secrets.THEME1_SSH_PRIVATE_KEY }}
```
